package view;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
/**
 *
 * 
 */
public class Kategori extends javax.swing.JFrame {
int baris = 0;
    static Object kolom[] = {"No", "ID Kategori", "Nama"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    DefaultComboBoxModel mdl = new DefaultComboBoxModel();
    /**
     * Creates new form DataKategori
     */
    public Kategori() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BHapus = new javax.swing.JButton();
        TIDKategori = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        TCari = new javax.swing.JTextField();
        BCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblKategori = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BEdit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TNamaKategori = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        TIDKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIDKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(TIDKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 192, -1));

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        getContentPane().add(BReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 70, -1));

        TCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCariActionPerformed(evt);
            }
        });
        getContentPane().add(TCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 166, -1));

        BCari.setText("Cari");
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });
        getContentPane().add(BCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        TblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblKategori);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 483, 145));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel1.setText("DATA KATEGORI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        getContentPane().add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 70, -1));

        jLabel3.setText("ID Kategori");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Nama Kategori");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        TNamaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(TNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 192, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 147, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Download free vector of Blue pink gradient blur background vector by Nunny about backgrounds, design background, gradient, abstract backgrounds, and blue 2619630.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -7, 530, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        int Pilihbaris = TblKategori.getSelectedRow();
        String IDKategori = tbl.getValueAt(Pilihbaris, 1).toString();

        DataKategori.HapusDataKategori(IDKategori);
        tbl.removeRow(Pilihbaris);
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus",
            "Pesan Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BHapusActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        String IDKategori = TIDKategori.getText();
        String NamaKategori = TNamaKategori.getText();
        if(IDKategori.isEmpty()){
            JOptionPane.showMessageDialog(this, "ID Kategori harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(NamaKategori.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Kategori harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int No = DataKategori.TambahDataKategori(IDKategori, NamaKategori);
            tbl.addRow(new Object[]{No,IDKategori, NamaKategori});
            TblKategori.setModel(tbl);
            
            TIDKategori.setText("");
            TNamaKategori.setText("");
        }
    }//GEN-LAST:event_BTambahActionPerformed
    
    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        String IDKategori = TIDKategori.getText();
        String NamaKategori = TNamaKategori.getText();

        DataKategori.UpdateDataKategori(IDKategori, NamaKategori);
        tbl.getDataVector().removeAllElements();

        String [][] data = DataKategori.getKategori();
        for(int i=0; i<data.length; i++){
            int no = i + 1;
            tbl.addRow(new Object[]{no, data[i][0], data[i][1]});
        }
        TblKategori.setModel(tbl);

        JOptionPane.showMessageDialog(this, "Data berhasil diedit",
            "Pesan Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
        
        TIDKategori.setEditable(true);
        TIDKategori.setText("");
        TNamaKategori.setText("");
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        TIDKategori.setEditable(true);
        TIDKategori.setText("");
        TNamaKategori.setText("");
    }//GEN-LAST:event_BResetActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        String kategori = TCari.getText();
        tbl.getDataVector().removeAllElements();

        String [][] data = DataKategori.CariObatHasilTransaksi(kategori);
        for (int i=0; i<data.length; i++){
            int no = i + 1;
            tbl.addRow(new Object[] {no, data[i][0], data[i][1]});
        }
        TblKategori.setModel(tbl);
        TCari.setText("");
    }//GEN-LAST:event_BCariActionPerformed

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        int Pilihbaris = TblKategori.getSelectedRow();
        String IDKategori = tbl.getValueAt(Pilihbaris, 1).toString();
        String NamaKategori = DataKategori.getDataKategori(IDKategori);

        TIDKategori.setText(IDKategori);
        TIDKategori.setEditable(false);
        TNamaKategori.setText(NamaKategori);
    }//GEN-LAST:event_BEditActionPerformed

    private void TIDKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIDKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDKategoriActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //GET DATA TABLE
        String [][] data = DataKategori.getKategori();
        for(int i=0; i<data.length; i++){
            int no = i + 1;
            tbl.addRow(new Object[]{no, data[i][0], data[i][1]});
        }
        TblKategori.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    private void TNamaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaKategoriActionPerformed

    private void TCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCari;
    private javax.swing.JButton BEdit;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JTextField TCari;
    private javax.swing.JTextField TIDKategori;
    private javax.swing.JTextField TNamaKategori;
    private javax.swing.JTable TblKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
