package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.*;
/**
 *
 * 
 */
public class Obat extends javax.swing.JFrame {

    /**
     * Creates new form DataObat
     */
    DefaultComboBoxModel mdl1 = new DefaultComboBoxModel();
    DefaultComboBoxModel mdl2 = new DefaultComboBoxModel();
    
    int baris = 0;
    static Object kolom[]= {"No", "ID Obat", "Kategori", "Suplier", "Nama Obat", "Harga"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    
    public Obat() {
        initComponents();
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelObat = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BEdit = new javax.swing.JButton();
        CKategori = new javax.swing.JComboBox<>();
        BHapus = new javax.swing.JButton();
        TNama = new javax.swing.JTextField();
        THarga = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        TCari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BCari = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CSuplier = new javax.swing.JComboBox<>();
        TIDObat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Kategori");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        TabelObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelObat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 511, 150));

        jLabel3.setText("Nama  Obat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        BEdit.setText("Edit");
        BEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditActionPerformed(evt);
            }
        });
        getContentPane().add(BEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 70, -1));

        CKategori.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CKategoriComponentShown(evt);
            }
        });
        CKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CKategoriActionPerformed(evt);
            }
        });
        getContentPane().add(CKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 200, -1));

        BHapus.setText("Hapus");
        BHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 70, -1));

        TNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaActionPerformed(evt);
            }
        });
        getContentPane().add(TNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 200, -1));
        getContentPane().add(THarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 200, -1));

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        getContentPane().add(BReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 70, -1));
        getContentPane().add(TCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel1.setText("DATA OBAT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        BCari.setText("Cari");
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });
        getContentPane().add(BCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel5.setText("Suplier");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        CSuplier.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CSuplierComponentShown(evt);
            }
        });
        getContentPane().add(CSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 200, -1));

        TIDObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIDObatActionPerformed(evt);
            }
        });
        getContentPane().add(TIDObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, -1));

        jLabel6.setText("Id Obat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Download free vector of Blue pink gradient blur background vector by Nunny about backgrounds, design background, gradient, abstract backgrounds, and blue 2619630.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditActionPerformed
        int Pilihbaris = TabelObat.getSelectedRow();
        String IDObat = tbl.getValueAt(Pilihbaris, 1).toString();

        String [][] data = DataObat.getDataObat(IDObat);
        String IDKategori = data[0][0];
        String Kategori = data[0][1];
        String IDSuplier = data[0][2];
        String Suplier = data[0][3];
        String NamaObat = data[0][4];
        String Harga = data[0][5];


        CKategori.setSelectedItem(IDKategori+" - "+Kategori);
        CSuplier.setSelectedItem(IDSuplier+" - "+Suplier);
        TIDObat.setText(IDObat);
        TIDObat.setEditable(false);
        TNama.setText(NamaObat);
        THarga.setText(Harga);
    }//GEN-LAST:event_BEditActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        int Pilihbaris = TabelObat.getSelectedRow();
        String IDObat = tbl.getValueAt(Pilihbaris, 1).toString();

        DataObat.DeleteObat(IDObat);
        tbl.removeRow(Pilihbaris);
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus",
            "Pesan Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BHapusActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        String Kategori = CKategori.getSelectedItem().toString();
        String[] pisahKategori = Kategori.split("-");
        String IDKategori = pisahKategori[0];
        String NamaKategori = pisahKategori[1];
        
        String Suplier = CSuplier.getSelectedItem().toString();
        String[] pisahSuplier = Suplier.split("-");
        String IDSuplier = pisahSuplier[0];
        String NamaSuplier = pisahSuplier[1];
        
        String IDObat = TIDObat.getText();
        String Nama = TNama.getText();
        String Harga = THarga.getText(); 

        if(IDObat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Id Obat harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(Nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(Harga.isEmpty()){
            JOptionPane.showMessageDialog(this, "Harga harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int No = DataObat.InsertObat(IDObat, IDKategori, IDSuplier, Nama, Harga);
            tbl.addRow(new Object[] {No, IDObat, NamaKategori, NamaSuplier, Nama, Harga});
            
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan",
                "Pesan Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
            TabelObat.setModel(tbl);
            TNama.setText("");
            THarga.setText("");
            TIDObat.setText("");
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        String Kategori = CKategori.getSelectedItem().toString();
        String[] pisahKategori = Kategori.split("-");
        String IDKategori = pisahKategori[0];
        String NamaKategori = pisahKategori[1];
        
        String Suplier = CSuplier.getSelectedItem().toString();
        String[] pisahSuplier = Suplier.split("-");
        String IDSuplier = pisahSuplier[0];
        String NamaSuplier = pisahSuplier[1];
        
        String IDObat = TIDObat.getText();
        String Nama = TNama.getText();
        String Harga = THarga.getText();
        
        DataObat.editObat(IDObat, Kategori, IDKategori, Suplier, IDSuplier, Nama, Harga);
        tbl.getDataVector().removeAllElements();
        
        //GET DATA TABLE
        String [][] data = DataObat.getObat();
        for(int i=0; i<data.length; i++){
            int no = i+1;
            tbl.addRow(new Object []{no, data[i][0], data[i][1], data[i][2], data[i][3], data[i][4]});
        }
        TabelObat.setModel(tbl);
        
        JOptionPane.showMessageDialog(this, "Data berhasil diedit",
                "Pesan Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
        TIDObat.setEditable(true);
        TIDObat.setText("");
        TNama.setText("");
        THarga.setText("");
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        TIDObat.setEditable(true);
        TIDObat.setText("");
        TNama.setText("");
        THarga.setText("");
    }//GEN-LAST:event_BResetActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        String kataKunci = TCari.getText();
        tbl.getDataVector().removeAllElements();

        String [][] data = DataObat.CariObat(kataKunci);
        for(int i=0; i<data.length; i++){
            int no = i+1;
            tbl.addRow(new Object []{no, data[i][0], data[i][1], data[i][2], data[i][3], data[i][4]});
        }
        TabelObat.setModel(tbl);
        TCari.setText("");
    }//GEN-LAST:event_BCariActionPerformed

    private void CKategoriComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CKategoriComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CKategoriComponentShown

    private void CSuplierComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CSuplierComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_CSuplierComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //GET DATA COMBOBOX
        String [] ListKategori = DataKategori.getListKategori();
        for(int i=0; i<ListKategori.length; i++){    
            mdl1.addElement(ListKategori[i]);
        }
        CKategori.setModel(mdl1);
        
        String [] ListSuplier = DataSuplier.getListSuplier();
        for(int i=0; i<ListSuplier.length; i++){
            mdl2.addElement(ListSuplier[i]);
        }
        CSuplier.setModel(mdl2);
        
        //GET DATA TABLE
        String [][] data = DataObat.getObat();
        for(int i=0; i<data.length; i++){
            int no = i+1;
            tbl.addRow(new Object []{no, data[i][0], data[i][1], data[i][2], data[i][3], data[i][4]});
        }
        TabelObat.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    private void TNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaActionPerformed

    private void CKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CKategoriActionPerformed

    private void TIDObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIDObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDObatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCari;
    private javax.swing.JButton BEdit;
    private javax.swing.JLabel BG;
    private javax.swing.JButton BHapus;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JComboBox<String> CKategori;
    private javax.swing.JComboBox<String> CSuplier;
    private javax.swing.JTextField TCari;
    private javax.swing.JTextField THarga;
    private javax.swing.JTextField TIDObat;
    private javax.swing.JTextField TNama;
    private javax.swing.JTable TabelObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
