package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.*;
/**
 *
 * 
 */
public class Suplier extends javax.swing.JFrame {
int baris = 0;
    static Object kolom[] = {"No","ID Suplier", "Nama", "Alamat", "Nomor Telepon"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    DefaultComboBoxModel mdl = new DefaultComboBoxModel();
    /**
     * Creates new form DataSuplier
     */
    public Suplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BHapus3 = new javax.swing.JButton();
        TNamaSuplier = new javax.swing.JTextField();
        BTambah = new javax.swing.JButton();
        BSimpan = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        TCari = new javax.swing.JTextField();
        BCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblSuplier = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BEdit1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TAlamatSuplier = new javax.swing.JTextField();
        TNoTelepon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TIDSuplier = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BHapus3.setText("Hapus");
        BHapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHapus3ActionPerformed(evt);
            }
        });
        getContentPane().add(BHapus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, -1));

        TNamaSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaSuplierActionPerformed(evt);
            }
        });
        getContentPane().add(TNamaSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 192, -1));

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        BSimpan.setText("Simpan");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        getContentPane().add(BReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 70, -1));
        getContentPane().add(TCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 166, -1));

        BCari.setText("Cari");
        BCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCariActionPerformed(evt);
            }
        });
        getContentPane().add(BCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        TblSuplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblSuplier);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 346, 524, 145));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel1.setText("DATA SUPLIER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        BEdit1.setText("Edit");
        BEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEdit1ActionPerformed(evt);
            }
        });
        getContentPane().add(BEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 70, -1));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        TAlamatSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAlamatSuplierActionPerformed(evt);
            }
        });
        getContentPane().add(TAlamatSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 192, -1));

        TNoTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNoTeleponActionPerformed(evt);
            }
        });
        getContentPane().add(TNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, -1));

        jLabel5.setText("No Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setText("ID Suplier");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        TIDSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIDSuplierActionPerformed(evt);
            }
        });
        getContentPane().add(TIDSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Download free vector of Blue pink gradient blur background vector by Nunny about backgrounds, design background, gradient, abstract backgrounds, and blue 2619630.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -3, 560, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BHapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapus3ActionPerformed
        int Pilihbaris = TblSuplier.getSelectedRow();
        String IDsuplier = tbl.getValueAt(Pilihbaris, 1).toString();

        DataSuplier.HapusData(IDsuplier);
        tbl.removeRow(Pilihbaris);
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus",
            "Pesan Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BHapus3ActionPerformed

    private void TNamaSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaSuplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaSuplierActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        String id = TIDSuplier.getText();
        String nama = TNamaSuplier.getText();
        String alamat = TAlamatSuplier.getText();
        String notelepon = TNoTelepon.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "ID Suplier harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Suplier harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(alamat.isEmpty()){
            JOptionPane.showMessageDialog(this, "Alamat Suplier harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(notelepon.isEmpty()){
            JOptionPane.showMessageDialog(this, "No Telepon harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int No = DataSuplier.TambahDataSuplier(id, nama, alamat, notelepon);
            tbl.addRow(new Object[]{No, id, nama, alamat, notelepon});
            TblSuplier.setModel(tbl);
            
            TNamaSuplier.setText("");
            TAlamatSuplier.setText("");
            TNoTelepon.setText("");
            TIDSuplier.setText("");
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        String IDSuplier = TIDSuplier.getText();
        String nama = TNamaSuplier.getText();
        String alamat = TAlamatSuplier.getText();
        String notelepon = TNoTelepon.getText();

        DataSuplier.UpdateDataSuplier(IDSuplier, nama, alamat, notelepon);
        tbl.getDataVector().removeAllElements();

        //GET DATA TABLE
        String [][] data = DataSuplier.getSuplier();
        for(int i=0; i<data.length; i++){
            int no = i + 1;
            tbl.addRow(new Object[]{no, data[i][0], data[i][1], data[i][2], data[i][3]});
        }
        TblSuplier.setModel(tbl);

        JOptionPane.showMessageDialog(this, "Data berhasil diedit",
            "Pesan Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
        
        TIDSuplier.setEditable(true);
        TIDSuplier.setText("");
        TNamaSuplier.setText("");
        TAlamatSuplier.setText("");
        TNoTelepon.setText("");
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        TIDSuplier.setEditable(true);
        TNoTelepon.setText("");
        TAlamatSuplier.setText("");
        TNamaSuplier.setText("");
        TIDSuplier.setText("");
    }//GEN-LAST:event_BResetActionPerformed

    private void BCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCariActionPerformed
        String kataKunci = TCari.getText();
        tbl.getDataVector().removeAllElements();

        String [][] data = DataSuplier.Caridatasuplier(kataKunci);
        for (int i=0; i<data.length; i++){
            int no = i + 1;
            tbl.addRow(new Object[] {no, data[i][0], data[i][1], data[i][2], data[i][3]});
        }
        TblSuplier.setModel(tbl);
        TCari.setText("");
    }//GEN-LAST:event_BCariActionPerformed

    private void BEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEdit1ActionPerformed
        int Pilihbaris = TblSuplier.getSelectedRow();
        String IDSuplier = tbl.getValueAt(Pilihbaris, 1).toString();
        String NamaSuplier = DataSuplier.EditNama(IDSuplier);
        String Alamat = DataSuplier.EditAlamat(IDSuplier);
        String telp = DataSuplier.EditNoTelp(IDSuplier);
        
        TIDSuplier.setText(IDSuplier);
        TIDSuplier.setEditable(false);
        TNamaSuplier.setText(NamaSuplier);
        TAlamatSuplier.setText(Alamat);
        TNoTelepon.setText(telp);
    }//GEN-LAST:event_BEdit1ActionPerformed

    private void TAlamatSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAlamatSuplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TAlamatSuplierActionPerformed

    private void TNoTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNoTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNoTeleponActionPerformed

    private void TIDSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIDSuplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIDSuplierActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //tabel
        String [][] data = DataSuplier.getSuplier();
        for(int i=0; i<data.length; i++){
            int no = i+1;
            tbl.addRow(new Object []{no, data[i][0], data[i][1], data[i][2], data[i][3]});
        }
        TblSuplier.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCari;
    private javax.swing.JButton BEdit1;
    private javax.swing.JLabel BG;
    private javax.swing.JButton BHapus3;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton BTambah;
    private javax.swing.JTextField TAlamatSuplier;
    private javax.swing.JTextField TCari;
    private javax.swing.JTextField TIDSuplier;
    private javax.swing.JTextField TNamaSuplier;
    private javax.swing.JTextField TNoTelepon;
    private javax.swing.JTable TblSuplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
